name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Run tests with coverage
      run: |
        go test -race -coverprofile=coverage.txt ./...
        go tool cover -func=coverage.txt

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.txt
        fail_ci_if_error: true